npmRegistryServer: "https://registry.npmjs.org/"
networkTimeout: 300000

nodeLinker: node-modules

npmScopes:
  electron:
    npmRegistryServer: "https://registry.npmjs.org/"
    npmAlwaysAuth: false

unsafeHttpWhitelist:
  - "*"

gitChecksumBehavior: ignore