name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build-and-release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "VERSION=${TAG_NAME#v}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Check for CHANGELOG.md
        id: check_changelog
        run: |
          if [ -f "CHANGELOG.md" ]; then
            echo "EXISTS=true" >> $GITHUB_OUTPUT
            echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_OUTPUT
            cat CHANGELOG.md >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "EXISTS=false" >> $GITHUB_OUTPUT
            echo "CHANGELOG_CONTENT=版本 ${GITHUB_REF#refs/tags/} 发布" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.check_changelog.outputs.CHANGELOG_CONTENT }}
          draft: false
          prerelease: false
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}